#!/bin/bash

rsync -vaz --delete --exclude-from /home/sites/berrics.staging/shell/exclude.txt  /home/sites/berrics.staging/ /home/sites/berrics/
/home/sites/berrics/shell/chmod-self;
rsync -vaz --delete --exclude-from /home/sites/berrics.staging/shell/exclude.txt  /home/sites/berrics.staging/ root@web2:/home/sites/berrics/


ssh root@web4 'apachectl -k graceful-stop';
sleep 4;
rsync -vaz --delete --exclude-from /home/sites/berrics.staging/shell/exclude.txt /home/sites/berrics.staging/ root@web4:/home/sites/berrics/
ssh root@web4 '/home/sites/berrics/shell/clear-cache-self; /home/sites/berrics/shell/chmod-self;';
ssh root@web4 '/sbin/service httpd start';

ssh root@web5 'apachectl -k graceful-stop';
sleep 4;
rsync -vaz --delete --exclude-from /home/sites/berrics.staging/shell/exclude.txt  /home/sites/berrics.staging/ root@web5:/home/sites/berrics/
ssh root@web5 '/home/sites/berrics/shell/clear-cache-self; /home/sites/berrics/shell/chmod-self;';
ssh root@web5 '/sbin/service httpd start';

ssh root@web6 'apachectl -k graceful-stop';
sleep 4;
rsync -vaz --delete --exclude-from /home/sites/berrics.staging/shell/exclude.txt  /home/sites/berrics.staging/ root@web6:/home/sites/berrics/
ssh root@web6 '/home/sites/berrics/shell/clear-cache-self; /home/sites/berrics/shell/chmod-self;';
ssh root@web6 '/sbin/service httpd start';

ssh root@web7 'apachectl -k graceful-stop';
sleep 4;
rsync -vaz --delete --exclude-from /home/sites/berrics.staging/shell/exclude.txt  /home/sites/berrics.staging/ root@web7:/home/sites/berrics/
ssh root@web7 '/home/sites/berrics/shell/clear-cache-self; /home/sites/berrics/shell/chmod-self;';
ssh root@web7 '/sbin/service httpd start';

ssh root@web8 'apachectl -k graceful-stop';
sleep 4;
rsync -vaz --delete --exclude-from /home/sites/berrics.staging/shell/exclude.txt  /home/sites/berrics.staging/ root@web8:/home/sites/berrics/
ssh root@web8 '/home/sites/berrics/shell/clear-cache-self; /home/sites/berrics/shell/chmod-self;';
ssh root@web8 '/sbin/service httpd start';

ssh root@web9 'apachectl -k graceful-stop';
sleep 4;
rsync -vaz --delete --exclude-from /home/sites/berrics.staging/shell/exclude.txt  /home/sites/berrics.staging/ root@web9:/home/sites/berrics/
ssh root@web9 '/home/sites/berrics/shell/clear-cache-self; /home/sites/berrics/shell/chmod-self;';
ssh root@web9 '/sbin/service httpd start';




#FLUSH THE MEMCACHE SERVER
ssh root@cacheserver 'echo "flush_all" | nc 127.0.0.1 11211';







