#!/bin/bash


/home/sites/berrics.shell/sync-dev-to-staging

/home/sites/berrics.shell/sync-berrics-from-staging



#rsync -vaz --delete --exclude-from /home/sites/berrics.shell/exclude.txt /home/sites/berrics.dev/ root@web5:/home/sites/berrics/
#rsync -vaz --delete --exclude-from /home/sites/berrics.shell/exclude.txt /home/sites/berrics.dev/ root@web6:/home/sites/berrics/
#rsync -vaz --delete --exclude-from /home/sites/berrics.shell/exclude.txt /home/sites/berrics.dev/ root@web7:/home/sites/berrics/
#rsync -vaz --delete --exclude-from /home/sites/berrics.shell/exclude.txt /home/sites/berrics.dev/ root@web8:/home/sites/berrics/
#rsync -vaz --delete --exclude-from /home/sites/berrics.shell/exclude.txt /home/sites/berrics.dev/ root@web9:/home/sites/berrics/
#rsync -vaz --delete --exclude-from /home/sites/berrics.shell/exclude.txt /home/sites/berrics.dev/ root@web10:/home/sites/berrics/
