#!/bin/bash
ssh root@web10 '/sbin/service httpd stop';
rsync -vaz --delete --exclude-from /home/sites/berrics.shell/exclude.txt /home/sites/berrics.dev/ 
root@web10:/home/sites/berrics/
ssh root@web10 '/sbin/service httpd start';
ssh root@web10 '/home/sites/berrics.shell/clear-cache-self';
