#!/bin/bash
exit 0;

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

#COMPRESS THEME CSS FILES
for F in $(find ${DIR}/../theberrics.com/public_html/app/webroot -iname '*.css' ! -iname '*.min.css'); 
do
	echo "FILENAME: "$F;
	NEW_FILE=${F/.css/.min.css};
	echo "NEW FILE: "$NEW_FILE;
	
	
	if [[ -e $NEW_FILE ]]; then
		echo "FILE EXISTS DELETE IT: "$NEW_FILE;
		rm $NEW_FILE;
	fi
	

	
done

