#!/bin/bash

FILES=$(git diff --cached --name-status);

echo $FILES>/tmp/files;

echo $FILES;
exit 1;

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
echo "Compressing CSS Files......"
#COMPRESS THEME CSS FILES
for F in $(find ${DIR}/../theberrics.com/public_html/app/webroot -iname '*.css' ! -iname '*.min.css'); 
do
	#echo "FILENAME: "$F;
	NEW_FILE=${F/.css/.min.css};
	#echo "NEW FILE: "$NEW_FILE;
	
	
	if [[ -e $NEW_FILE ]]; then
		#echo -n "FILE EXISTS DELETE IT: "$NEW_FILE;
		rm $NEW_FILE;
	fi
	
	#CREATE THE FILE
	java -jar ${DIR}/yuicompressor-2.4.7.jar --type css -o ${NEW_FILE} ${F};
	
	
	if [[ -e $NEW_FILE ]]; then
		echo "NEW MIN FILE CREATED: "$NEW_FILE;
		git add ${NEW_FILE}
	fi
	
done
echo "CSS Compression Completed"
echo "";
echo  "Compressing JS files........"

for F in $(find ${DIR}/../theberrics.com/public_html/app/webroot -iname '*.js' ! -iname '*.min.js'); 
do
	#echo "FILENAME: "$F;
	NEW_FILE=${F/.js/.min.js};
	#echo "NEW FILE: "$NEW_FILE;
	
	
	if [[ -e $NEW_FILE ]]; then
		#echo -n "FILE EXISTS DELETE IT: "$NEW_FILE;
		rm $NEW_FILE;
	fi
	
	#CREATE THE FILE
	java -jar ${DIR}/yuicompressor-2.4.7.jar --type js --nomunge --preserve-semi -o ${NEW_FILE} ${F};

	
	if [[ -e $NEW_FILE ]]; then
		echo "NEW MIN FILE CREATED: "$NEW_FILE;
		git add ${NEW_FILE}
	fi
	
done
echo "Completed JS Compression"
echo "";